# Generated by Django 3.2.11 on 2022-01-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.BooleanField(default=False),
        ),
    ]
